/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_math.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
multiply_1(myoperands *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MULTIPLY,
		(xdrproc_t) xdr_myoperands, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
power_1(myoperands *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, POWER,
		(xdrproc_t) xdr_myoperands, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
logn_1(myoperands *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, LOGN,
		(xdrproc_t) xdr_myoperands, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
largest_prime_divisor_1(myoperands *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, LARGEST_PRIME_DIVISOR,
		(xdrproc_t) xdr_myoperands, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
