/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_math.h"

bool_t
xdr_myoperands (XDR *xdrs, myoperands *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->arr.arr_val, (u_int *) &objp->arr.arr_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->argument))
		 return FALSE;
	return TRUE;
}
